$(function() {

  $('#about-trigger').click(function(){
    $('#about-card').addClass('is-visible');
    $('#clear-trigger').addClass('is-visible');
  });
  $('#contact-trigger').click(function(){
    $('#contact-card').addClass('is-visible');
    $('#clear-trigger').addClass('is-visible');
  });
  $('#news-trigger').click(function(){
    $('#news-card').addClass('is-visible');
    $('#clear-trigger').addClass('is-visible');
  });
  $('#follow-trigger').click(function(){
    $('#follow-card').addClass('is-visible');
    $('#clear-trigger').addClass('is-visible');
  });
  $('#clear-trigger').click(function(){
    $('#about-card').removeClass('is-visible');
    $('#contact-card').removeClass('is-visible');
    $('#news-card').removeClass('is-visible');
    $('#follow-card').removeClass('is-visible');
    $('#clear-trigger').removeClass('is-visible');
  });
  $('#about-banner-trigger').click(function(){
    $('#about-card').addClass('is-visible');
    $('#clear-trigger').addClass('is-visible');
    $('#contact-card').removeClass('is-visible');
    $('#news-card').removeClass('is-visible');
    $('#follow-card').removeClass('is-visible');
  });
  $('#contact-banner-trigger').click(function(){
    $('#contact-card').addClass('is-visible');
    $('#clear-trigger').addClass('is-visible');
    $('#about-card').removeClass('is-visible');
    $('#news-card').removeClass('is-visible');
    $('#follow-card').removeClass('is-visible');
  });
  $('#news-banner-trigger').click(function(){
    $('#news-card').addClass('is-visible');
    $('#clear-trigger').addClass('is-visible');
    $('#about-card').removeClass('is-visible');
    $('#contact-card').removeClass('is-visible');
    $('#follow-card').removeClass('is-visible');
  });
  $('#follow-banner-trigger').click(function(){
    $('#follow-card').addClass('is-visible');
    $('#clear-trigger').addClass('is-visible');
    $('#about-card').removeClass('is-visible');
    $('#news-card').removeClass('is-visible');
    $('#contact-card').removeClass('is-visible');
  });

});
